defaults:
  - data: afhqv2
  - model: wgan_gp
  - logging: mlflow
  - _self_

global_seed: 42
seed_workers: true
devices: 1

train:
  log_every_n_steps: 10
  enable_checkpointing: false
  enable_model_summary: true
  deterministic: true
